### ISSUE TITLE
Feature request: option to parse port forwarding and users

### ISSUE THREAD

**Issue by stv-io** [surminus/pfsense-parse#1]
❤️ have been looking for something like this for ages 😄 

Just stumbled upon this repo and have wrapped it around in a simple docker container built from https://hub.docker.com/r/_/ruby/.

Would be great if this tool could also parse 
 - port forwarding rules (currently only 1:1 NAT rules are displayed
 - users defined locally on the pfsense firewall

**Comment by stv-io** [comment]
I implemented this feature and would like to submit a PR if you're interested @surminus 😄

**Comment by surminus** [comment]
@sacasumo I actually used this for a project quite some time ago and no longer have to manage any pfsenses. I'd recommend forking it and maintaining if you're using it. 

I wrote it to help me learn a little ruby so it could probably be vastly improved either way! Glad it's helped someone else out :)
